/**
 * CAE-11.12-W2 — Canonical knowledge entity registry (ADP-001)
 */
export const CANONICAL_KNOWLEDGE_ENTITIES = [
  "KnowledgeDomain",
  "KnowledgeCollection",
  "KnowledgeArtifact",
  "KnowledgeVersion",
  "KnowledgeClaim",
  "Source",
  "Citation",
  "EvidenceReference",
  "KnowledgeRelationship",
  "KnowledgeReview",
  "KnowledgeApproval",
  "Course",
  "Module",
  "Lesson",
  "LearningObject",
  "LearningPath",
  "LearningEnrollment",
  "LearningCompletion",
  "LearningProgress",
  "Skill",
  "Competency",
  "CompetencyLevel",
  "HumanCompetencyRecord",
  "CompetencyEvidence",
  "Assessment",
  "AssessmentAttempt",
  "AssessmentResult",
  "AssessmentQuestion",
  "Certification",
  "CertificationAward",
  "CertificationRequirement",
  "Playbook",
  "StandardOperatingProcedure",
  "ResearchProject",
  "ResearchFinding",
  "InstitutionalInsight",
  "InstitutionalLesson",
  "InstitutionalMemoryRecord",
  "KnowledgeTranslation",
  "TutorConversation",
  "AIKnowledgeSuggestion",
  "HumanReviewDecision",
  "KnowledgeConflict",
  "KnowledgeGap",
  "KnowledgeCorrection",
  "KnowledgeSteward",
  "StewardshipAssignment",
  "LearningPathStep",
  "CoursePrerequisite",
  "KnowledgeAttachment",
  "LearningBadge",
  "KnowledgeTag",
  "KnowledgeVersionAudit",
  "KnowledgeHistoryEvent",
] as const;

export type CanonicalKnowledgeEntity = (typeof CANONICAL_KNOWLEDGE_ENTITIES)[number];

export const ENTITY_REGISTRY_META: Record<
  CanonicalKnowledgeEntity,
  { lifecycle: boolean; versioned: boolean; audited: boolean; subsystem: string }
> = {
  KnowledgeDomain: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  KnowledgeCollection: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  KnowledgeArtifact: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  KnowledgeVersion: { lifecycle: false, versioned: false, audited: true, subsystem: "knowledge" },
  KnowledgeClaim: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  Source: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  Citation: { lifecycle: true, versioned: false, audited: true, subsystem: "knowledge" },
  EvidenceReference: { lifecycle: true, versioned: false, audited: true, subsystem: "knowledge" },
  KnowledgeRelationship: { lifecycle: false, versioned: false, audited: true, subsystem: "knowledge" },
  KnowledgeReview: { lifecycle: true, versioned: false, audited: true, subsystem: "knowledge" },
  KnowledgeApproval: { lifecycle: true, versioned: false, audited: true, subsystem: "knowledge" },
  Course: { lifecycle: true, versioned: true, audited: true, subsystem: "learning" },
  Module: { lifecycle: true, versioned: true, audited: true, subsystem: "learning" },
  Lesson: { lifecycle: true, versioned: true, audited: true, subsystem: "learning" },
  LearningObject: { lifecycle: true, versioned: true, audited: true, subsystem: "learning" },
  LearningPath: { lifecycle: true, versioned: true, audited: true, subsystem: "learning" },
  LearningEnrollment: { lifecycle: true, versioned: false, audited: true, subsystem: "learning" },
  LearningCompletion: { lifecycle: true, versioned: false, audited: true, subsystem: "learning" },
  LearningProgress: { lifecycle: false, versioned: false, audited: true, subsystem: "learning" },
  Skill: { lifecycle: true, versioned: true, audited: true, subsystem: "competency" },
  Competency: { lifecycle: true, versioned: true, audited: true, subsystem: "competency" },
  CompetencyLevel: { lifecycle: true, versioned: true, audited: true, subsystem: "competency" },
  HumanCompetencyRecord: { lifecycle: true, versioned: false, audited: true, subsystem: "competency" },
  CompetencyEvidence: { lifecycle: false, versioned: false, audited: true, subsystem: "competency" },
  Assessment: { lifecycle: true, versioned: true, audited: true, subsystem: "learning" },
  AssessmentAttempt: { lifecycle: true, versioned: false, audited: true, subsystem: "learning" },
  AssessmentResult: { lifecycle: true, versioned: false, audited: true, subsystem: "learning" },
  AssessmentQuestion: { lifecycle: true, versioned: true, audited: true, subsystem: "learning" },
  Certification: { lifecycle: true, versioned: true, audited: true, subsystem: "certification" },
  CertificationAward: { lifecycle: true, versioned: false, audited: true, subsystem: "certification" },
  CertificationRequirement: { lifecycle: true, versioned: true, audited: true, subsystem: "certification" },
  Playbook: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  StandardOperatingProcedure: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  ResearchProject: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  ResearchFinding: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  InstitutionalInsight: { lifecycle: true, versioned: true, audited: true, subsystem: "memory" },
  InstitutionalLesson: { lifecycle: true, versioned: true, audited: true, subsystem: "memory" },
  InstitutionalMemoryRecord: { lifecycle: true, versioned: true, audited: true, subsystem: "memory" },
  KnowledgeTranslation: { lifecycle: true, versioned: true, audited: true, subsystem: "knowledge" },
  TutorConversation: { lifecycle: true, versioned: false, audited: true, subsystem: "ai" },
  AIKnowledgeSuggestion: { lifecycle: true, versioned: false, audited: true, subsystem: "ai" },
  HumanReviewDecision: { lifecycle: true, versioned: false, audited: true, subsystem: "governance" },
  KnowledgeConflict: { lifecycle: true, versioned: false, audited: true, subsystem: "governance" },
  KnowledgeGap: { lifecycle: true, versioned: false, audited: true, subsystem: "knowledge" },
  KnowledgeCorrection: { lifecycle: true, versioned: true, audited: true, subsystem: "governance" },
  KnowledgeSteward: { lifecycle: true, versioned: false, audited: true, subsystem: "stewardship" },
  StewardshipAssignment: { lifecycle: true, versioned: false, audited: true, subsystem: "stewardship" },
  LearningPathStep: { lifecycle: false, versioned: false, audited: true, subsystem: "learning" },
  CoursePrerequisite: { lifecycle: false, versioned: false, audited: true, subsystem: "learning" },
  KnowledgeAttachment: { lifecycle: false, versioned: false, audited: true, subsystem: "knowledge" },
  LearningBadge: { lifecycle: true, versioned: false, audited: true, subsystem: "learning" },
  KnowledgeTag: { lifecycle: false, versioned: false, audited: false, subsystem: "knowledge" },
  KnowledgeVersionAudit: { lifecycle: false, versioned: false, audited: true, subsystem: "knowledge" },
  KnowledgeHistoryEvent: { lifecycle: false, versioned: false, audited: true, subsystem: "knowledge" },
};

export const PARENT_CHILD_MATRIX: Record<string, string | null> = {
  KnowledgeDomain: "Institution",
  KnowledgeCollection: "KnowledgeDomain",
  KnowledgeArtifact: "KnowledgeCollection",
  KnowledgeVersion: "KnowledgeArtifact",
  KnowledgeClaim: "KnowledgeArtifact",
  Source: null,
  Citation: "KnowledgeClaim",
  EvidenceReference: "KnowledgeClaim",
  KnowledgeRelationship: null,
  KnowledgeReview: "KnowledgeArtifact",
  KnowledgeApproval: "KnowledgeArtifact",
  Course: "KnowledgeDomain",
  Module: "Course",
  Lesson: "Module",
  LearningObject: "Lesson",
  LearningPath: "KnowledgeDomain",
  LearningEnrollment: "Course",
  LearningCompletion: "Course",
  LearningProgress: "LearningEnrollment",
  Skill: "KnowledgeDomain",
  Competency: "Skill",
  CompetencyLevel: "Competency",
  HumanCompetencyRecord: "Competency",
  CompetencyEvidence: "HumanCompetencyRecord",
  Assessment: "Competency",
  AssessmentAttempt: "Assessment",
  AssessmentResult: "AssessmentAttempt",
  AssessmentQuestion: "Assessment",
  Certification: "Competency",
  CertificationAward: "Certification",
  CertificationRequirement: "Certification",
  Playbook: "KnowledgeArtifact",
  StandardOperatingProcedure: "KnowledgeArtifact",
  ResearchProject: "KnowledgeDomain",
  ResearchFinding: "ResearchProject",
  InstitutionalInsight: "InstitutionalMemoryRecord",
  InstitutionalLesson: "KnowledgeDomain",
  InstitutionalMemoryRecord: "Institution",
  KnowledgeTranslation: "KnowledgeArtifact",
  TutorConversation: "Course",
  AIKnowledgeSuggestion: "KnowledgeArtifact",
  HumanReviewDecision: null,
  KnowledgeConflict: "KnowledgeClaim",
  KnowledgeGap: "KnowledgeDomain",
  KnowledgeCorrection: "KnowledgeArtifact",
  KnowledgeSteward: "KnowledgeDomain",
  StewardshipAssignment: "KnowledgeArtifact",
  LearningPathStep: "LearningPath",
  CoursePrerequisite: "Course",
  KnowledgeAttachment: "KnowledgeArtifact",
  LearningBadge: "LearningCompletion",
  KnowledgeTag: null,
  KnowledgeVersionAudit: "KnowledgeArtifact",
  KnowledgeHistoryEvent: null,
};

export const REQUIRED_REPOSITORIES = [
  "CanonicalKnowledgeArtifactRepository",
  "CanonicalKnowledgeClaimRepository",
  "CanonicalCourseRepository",
  "CanonicalCompetencyRepository",
  "CanonicalCertificationRepository",
  "CanonicalEvidenceRepository",
  "CanonicalRelationshipRepository",
  "CanonicalVersionRepository",
  "CanonicalSearchIndexer",
  "CanonicalEventPublisher",
] as const;

export const COM_002_BOUNDARY_ENTITIES = [
  "Conversation",
  "Message",
  "CommunicationKnowledge",
] as const;

export function getEntityRegistry() {
  return {
    protocol: "11.12-W2",
    subsystem: "ADP-001",
    entities: CANONICAL_KNOWLEDGE_ENTITIES,
    entity_count: CANONICAL_KNOWLEDGE_ENTITIES.length,
    meta: ENTITY_REGISTRY_META,
    parent_child: PARENT_CHILD_MATRIX,
    repositories: REQUIRED_REPOSITORIES,
    com_002_boundary: COM_002_BOUNDARY_ENTITIES,
  };
}
