/**
 * V1-CERT-PASS-01 — Master capability catalog (vision inventory).
 * Read-only audit input. No product behavior.
 */

/** @typedef {{ id: string, track: string, domain: string, domain_id: number, name: string, vision: string, humans: string[], journey: string, ui_keys: string[], api_keys: string[], lib_keys: string[], doc_keys: string[], test_keys: string[], infra_only?: boolean }} CapDef */

/** @type {CapDef[]} */
export const CAPABILITIES = [];

function add(track, domain_id, domain, items) {
  for (const item of items) {
    const [suffix, name, vision, humans, journey, ui = [], api = [], lib = [], doc = [], test = [], infra_only = false] = item;
    CAPABILITIES.push({
      id: `${track}-${String(domain_id).padStart(2, '0')}-${suffix}`,
      track,
      domain,
      domain_id,
      name,
      vision,
      humans: humans.split('|'),
      journey,
      ui_keys: ui,
      api_keys: api,
      lib_keys: lib,
      doc_keys: doc,
      test_keys: test,
      infra_only,
    });
  }
}

// Domain 1 — Access, Invitation, Verified Identity (Track B / A)
add('B', 1, 'Access, Invitation, and Verified Identity', [
  ['INV-001', 'Invitation-only entry', 'Platform entry requires invitation', 'Guest|Invited Human', 'Invite link → land → create', ['invite', 'invitations'], ['invitations', 'auth'], ['auth/invitations'], ['launch', 'identity'], ['auth']],
  ['INV-002', 'Invite-code ownership', 'Invite codes owned by verified sponsors', 'Administrator|Sponsor', 'Sponsor creates invite', ['identity/sponsor', 'identity/invitations'], ['invitations'], ['auth/invitations'], [], []],
  ['INV-003', 'Referrer attribution', 'Inviter remains attributable after accept', 'Administrator|Sponsored Human', 'Accept → lineage', ['invitations/accept', 'invite'], ['invitations'], ['auth/invitations'], [], []],
  ['INV-004', 'Human identity verification', 'Verified Human identity before trust elevation', 'Invited Human|Administrator', 'Verification flow', ['identity/verification', 'identity/verifications'], ['identity-trust', 'identity'], ['identity'], [], []],
  ['INV-005', 'Public Human name enforcement', 'Public Human name is required and governed', 'Invited Human', 'Profile name rules', ['identity'], ['identity'], ['identity'], [], []],
  ['INV-006', 'Alias governance', 'Aliases governed under verified identity', 'Invited Human|Administrator', 'Alias set/review', ['identity'], ['identity'], [], [], []],
  ['INV-007', 'Secondary verification', 'Additional verification pathways exist', 'Administrator|Invited Human', 'Secondary verify', ['identity/verification'], ['identity-trust'], [], [], []],
  ['INV-008', 'Removal or review pathway', 'Identity appeals/review exist', 'Administrator|Human', 'Appeal/review', ['identity/appeals', 'identity/cases'], ['identity-trust'], [], [], []],
  ['INV-009', 'Invitation expiration', 'Invitations expire', 'Administrator|Sponsored Human', 'Expired invite denied', ['invite', 'invitations'], ['invitations'], ['auth/invitations'], [], []],
  ['INV-010', 'Invitation revocation', 'Invitations can be revoked', 'Administrator|Sponsor', 'Revoke invite', ['identity/invitations'], ['invitations'], ['auth/invitations'], [], []],
  ['INV-011', 'Invite abuse controls', 'Abuse controls on invite creation/use', 'Administrator', 'Rate/abuse checks', [], ['invitations'], ['auth/invitations'], [], []],
  ['INV-012', 'User lineage and sponsor traceability', 'Sponsor lineage persists', 'Administrator|Human', 'Trace sponsor', ['identity'], ['invitations', 'identity'], ['auth/invitations'], [], []],
  ['INV-013', 'Organization-specific invitations', 'Invites scoped to organizations', 'Administrator|Sponsor', 'Org invite', ['identity/invitations', 'identity/institutions'], ['invitations', 'institutions'], [], [], []],
  ['INV-014', 'Team and Mission invitations', 'Invites to teams/missions', 'Team Lead|Organizer', 'Mission/team invite', ['initiatives', 'communications/missions'], ['invitations', 'missions'], [], [], []],
  ['INV-015', 'Email invitation', 'Email delivery of invites', 'Sponsor', 'Send email invite', ['identity/sponsor'], ['invitations'], [], [], []],
  ['INV-016', 'SMS invitation', 'SMS delivery of invites', 'Sponsor', 'Send SMS invite', [], ['invitations'], [], [], []],
  ['INV-017', 'QR invitation', 'QR invitation path', 'Sponsor|Guest', 'Scan QR → invite', [], ['invitations'], [], [], []],
  ['INV-018', 'Shareable invitation link', 'Shareable invite URL', 'Sponsor|Guest', 'Copy link → accept', ['invite'], ['invitations'], [], [], []],
  ['INV-019', 'Invitation acceptance tracking', 'Acceptance tracked', 'Administrator|Sponsor', 'View accept status', ['identity/invitations'], ['invitations'], [], [], []],
  ['INV-020', 'Invitation conversion analytics', 'Conversion analytics for invites', 'Administrator', 'Analytics view', [], ['analytics', 'invitations'], [], [], []],
  ['INV-021', 'Duplicate identity prevention', 'Duplicate Human prevention', 'Administrator', 'Dedupe check', ['identity'], ['identity'], [], [], []],
  ['INV-022', 'Account recovery', 'Account recovery path', 'Human', 'Forgot password/recovery', ['forgot-password'], ['auth'], ['auth'], [], []],
  ['INV-023', 'Session recovery', 'Session recovery/refresh', 'Human', 'Return visit resumes', [], ['auth'], ['auth/session'], [], []],
  ['INV-024', 'Device management', 'Device management for sessions', 'Human', 'Manage devices', ['account/security'], ['auth'], ['auth'], [], []],
  ['INV-025', 'Multi-organization identity', 'One Human across orgs with switching', 'Human|Administrator', 'Select org / switch', [], ['institutions', 'auth'], ['auth'], [], []],
  ['INV-026', 'Password login/register', 'Password auth available', 'Human', 'Login/register', ['login', 'register'], ['auth'], ['auth'], [], []],
  ['INV-027', 'Passwordless login', 'Passwordless path', 'Human', 'Passwordless', ['passwordless'], ['auth'], ['auth'], [], []],
  ['INV-028', 'MFA setup', 'MFA available', 'Human', 'MFA setup', ['mfa'], ['auth'], ['auth/mfa'], [], []],
]);

// Domain 2 — LocalBrain (Track B / E)
add('B', 2, 'LocalBrain and Personal Context', [
  ['LB-001', 'One Human / one LocalBrain', 'Canonical one LocalBrain per Human', 'Human', 'Identity → LocalBrain', [], ['localbrain'], ['living/localbrain'], ['LOCALBRAIN'], ['11.7:w1']],
  ['LB-002', 'LocalBrain creation', 'LocalBrain created for Human', 'Human', 'First-run create', [], ['localbrain'], ['living/localbrain'], [], ['11.7:w1']],
  ['LB-003', 'Personal memory', 'Personal memory store', 'Human', 'Remember preference/fact', [], ['localbrain/memory'], ['living/localbrain'], [], ['11.7:w1']],
  ['LB-004', 'Working memory', 'Working memory', 'Human', 'Session working set', [], ['localbrain'], ['living/localbrain'], [], []],
  ['LB-005', 'Temporary memory', 'Temporary memory', 'Human', 'Ephemeral memory', [], ['localbrain'], ['living/localbrain'], [], []],
  ['LB-006', 'Long-term memory', 'Long-term memory', 'Human', 'Persist long-term', [], ['localbrain/memory'], ['living/localbrain'], [], []],
  ['LB-007', 'Memory promotion', 'Promote personal→org memory', 'Human|Administrator', 'Promote memory', [], ['promote-memory'], ['living/localbrain'], [], []],
  ['LB-008', 'Memory correction', 'Correct memory', 'Human', 'Edit memory', [], ['localbrain/memory'], ['living/localbrain'], [], []],
  ['LB-009', 'Memory retention controls', 'Delete/retain controls', 'Human', 'Delete memory', [], ['localbrain/memory'], ['living/localbrain'], [], []],
  ['LB-010', 'Active Institution context', 'Active institution in LocalBrain', 'Human', 'Switch org refreshes context', [], ['localbrain/context'], ['living/context'], [], ['11.7:w2']],
  ['LB-011', 'Active Mission context', 'Active mission context', 'Human|Organizer', 'Mission context load', [], ['localbrain/context'], ['living/context'], [], []],
  ['LB-012', 'Calendar context', 'Calendar feeds LocalBrain context', 'Human', 'Day context from calendar', [], ['localbrain/context', 'calendar'], ['living/context'], [], []],
  ['LB-013', 'Meeting context', 'Meeting context in LocalBrain', 'Human', 'Meeting prep context', [], ['localbrain', 'meetings'], ['living'], [], []],
  ['LB-014', 'Role context', 'Role-aware LocalBrain', 'Human', 'Role context', [], ['localbrain/context'], ['living/context'], [], []],
  ['LB-015', 'Privacy boundaries', 'Private memory boundaries', 'Human', 'Private vs shared', [], ['localbrain'], ['living/localbrain'], [], []],
  ['LB-016', 'Cross-Institution isolation', 'No cross-tenant memory leak', 'Human|Administrator', 'Org A memory hidden in Org B', [], ['localbrain', 'kernel'], ['living/localbrain', 'living/kernel'], [], []],
  ['LB-017', 'Context correction', 'Human can correct context', 'Human', 'Correct context', [], ['localbrain/context'], ['living/context'], [], []],
  ['LB-018', 'Human override', 'Human override of AI context', 'Human', 'Override suggestion', [], ['localbrain', 'partnership'], ['living'], [], []],
  ['LB-019', 'LocalBrain workspace integration', 'LocalBrain in daily workspace UI', 'Human', 'Open LocalBrain in workspace', ['localbrain'], ['localbrain'], ['living/localbrain'], [], []],
  ['LB-020', 'Personal preference storage', 'Preferences persist', 'Human', 'Save preferences', ['notifications/preferences'], ['localbrain/preferences'], ['living/localbrain'], [], []],
  ['LB-021', 'Conversational Spanish', 'LocalBrain Spanish conversation', 'Human', 'Speak Spanish with LB', [], ['localbrain'], [], ['spanish', 'Spanish'], []],
  ['LB-022', 'Accessibility preferences', 'A11y prefs on LocalBrain', 'Human', 'Set a11y prefs', [], ['localbrain/preferences'], [], ['accessib'], []],
  ['LB-023', 'LocalBrain timeline', 'Personal timeline', 'Human', 'View timeline', [], ['localbrain/timeline'], ['living/localbrain'], [], []],
]);

// Domain 3 — Onboarding (Track B / J)
add('B', 3, 'Onboarding and First-Run Experience', [
  ['ONB-001', 'Invitation landing page', 'Invite landing explains offer', 'Invited Human', 'Open invite URL', ['invite'], ['invitations'], [], ['onboarding'], []],
  ['ONB-002', 'Inviter identity on landing', 'Shows who invited', 'Invited Human', 'See inviter', ['invite'], ['invitations'], [], [], []],
  ['ONB-003', 'Reason for invitation', 'Shows why invited', 'Invited Human', 'See reason', ['invite'], [], [], [], []],
  ['ONB-004', 'Account creation', 'Create account from invite', 'Invited Human', 'Register', ['register', 'invite'], ['auth'], [], [], []],
  ['ONB-005', 'Identity setup', 'Identity setup on first run', 'Invited Human', 'Setup identity', ['identity', 'onboarding'], [], [], [], []],
  ['ONB-006', 'Organization introduction', 'Org intro in onboarding', 'Invited Human', 'Meet org', ['onboarding', 'join'], [], [], ['onboarding'], []],
  ['ONB-007', 'Role explanation', 'Role explained', 'Invited Human', 'Understand role', ['onboarding'], [], [], ['ROLE_BASED'], []],
  ['ONB-008', 'Team introduction', 'Team intro', 'Invited Human', 'Meet team', ['onboarding'], [], [], [], []],
  ['ONB-009', 'LocalBrain introduction', 'Introduce LocalBrain at first run', 'Invited Human', 'Meet LocalBrain', ['onboarding', 'localbrain'], ['localbrain'], [], [], []],
  ['ONB-010', 'Workspace initialization', 'Workspace initialized', 'Invited Human', 'Land in workspace', ['onboarding'], [], [], [], []],
  ['ONB-011', 'First meaningful action', 'Guided first productive action', 'Invited Human', 'Complete first task', ['onboarding'], [], [], [], []],
  ['ONB-012', 'Guided first session', 'Guided session', 'Invited Human', 'Guided tour', ['onboarding'], [], [], [], []],
  ['ONB-013', 'First-day follow-up', 'First-day follow-up', 'Invited Human', 'Day-1 nudge', [], [], [], [], []],
  ['ONB-014', 'First-week journey', 'First-week journey', 'Invited Human', 'Week-1 path', [], [], [], [], []],
  ['ONB-015', 'Drop-off recovery', 'Recover abandoned onboarding', 'Invited Human', 'Resume onboarding', ['onboarding'], [], [], [], []],
  ['ONB-016', 'Mobile onboarding', 'Mobile onboarding works', 'Invited Human', 'Onboard on phone', ['onboarding', 'invite'], [], [], [], []],
  ['ONB-017', 'Tablet onboarding', 'Tablet onboarding', 'Invited Human', 'Onboard on tablet', ['onboarding'], [], [], [], []],
  ['ONB-018', 'Spanish onboarding', 'Full onboarding in Spanish', 'Invited Human', 'Onboard in ES', [], [], [], ['spanish', 'Spanish'], []],
  ['ONB-019', 'Accessibility path', 'Accessible onboarding', 'Invited Human', 'A11y onboard', ['onboarding'], [], [], ['accessib'], []],
  ['ONB-020', 'Time to first success', '≤10 min invite→productive measurable', 'Invited Human', 'Invite→success', ['invite', 'onboarding'], [], [], [], []],
]);

// Domain 4 — Daily Workspace (Track C)
add('C', 4, 'Daily Workspace and Navigation', [
  ['DAY-001', 'Daily briefing', 'Daily briefing surface', 'Executive|Organizer|Human', 'Open briefing', ['communications/brief'], ['localbrain/briefings', 'communications'], ['assemble-daily-brief', 'executive-assistant'], [], []],
  ['DAY-002', 'Today view', 'Today priorities view', 'Human|Organizer', 'Open today', ['today'], ['organizer', 'objectives'], [], [], []],
  ['DAY-003', 'My Day timeline', 'Personal day timeline', 'Human', 'View My Day', [], ['organizer', 'timeline'], [], [], []],
  ['DAY-004', 'Current priorities', 'Current priorities list', 'Human|Executive', 'See priorities', ['today', 'operations'], ['organizer'], [], [], []],
  ['DAY-005', 'Upcoming meetings', 'Upcoming meetings in workspace', 'Human', 'See meetings', ['communications/meetings', 'communications/brief'], ['calendar', 'meetings'], [], [], []],
  ['DAY-006', 'Active Missions', 'Active missions in daily surface', 'Organizer|Human', 'See active missions', ['operations', 'missions'], ['organizer', 'missions'], [], [], []],
  ['DAY-007', 'Waiting-on items', 'Waiting-on tracker', 'Human|Executive', 'See waiting-on', [], ['organizer', 'commitments'], [], [], []],
  ['DAY-008', 'Decisions awaiting action', 'Pending decisions', 'Executive|Human', 'Act on decision', ['communications/decisions'], ['decisions'], [], [], []],
  ['DAY-009', 'Announcements', 'Announcements surface', 'Human', 'Read announcement', ['communications'], ['communications'], [], [], []],
  ['DAY-010', 'Notifications', 'In-app notifications', 'Human', 'Open notifications', ['notifications', 'communications/notifications'], ['notifications'], [], [], []],
  ['DAY-011', 'Search', 'Global/workspace search', 'Human', 'Search', ['communications/search'], ['search'], [], [], []],
  ['DAY-012', 'Command palette', 'Command palette', 'Human', 'Cmd-K actions', [], [], [], [], []],
  ['DAY-013', 'Recent work', 'Recent work list', 'Human', 'Resume recent', [], [], [], [], []],
  ['DAY-014', 'Bookmarks', 'Bookmarks', 'Human', 'Bookmark item', [], [], [], [], []],
  ['DAY-015', 'Notes', 'Personal notes in workspace', 'Human', 'Write note', [], [], [], [], []],
  ['DAY-016', 'Focus mode', 'Focus mode', 'Human', 'Enter focus', [], ['focus-sessions'], ['living/context'], [], []],
  ['DAY-017', 'End-of-day review', 'EOD review', 'Human', 'EOD review', [], ['organizer'], [], [], []],
  ['DAY-018', 'Tomorrow preparation', 'Prepare tomorrow', 'Human', 'Prep tomorrow', [], ['organizer', 'briefings'], [], [], []],
  ['DAY-019', 'Mobile workspace', 'Mobile daily workspace', 'Human', 'Use on mobile', [], [], [], [], []],
  ['DAY-020', 'Tablet workspace', 'Tablet daily workspace', 'Human', 'Use on tablet', [], [], [], [], []],
  ['DAY-021', 'Large-display mode', 'Large display mode', 'Executive', 'Wall/TV mode', [], [], [], [], []],
  ['DAY-022', 'Consistent global navigation', 'Consistent nav across surfaces', 'Human', 'Navigate product', [], [], [], ['USER_EXPERIENCE'], []],
  ['DAY-023', 'Empty states', 'Meaningful empty states', 'Human', 'Empty inbox/state', [], [], [], [], []],
  ['DAY-024', 'Loading states', 'Loading states', 'Human', 'See loading', [], [], [], [], []],
  ['DAY-025', 'Error recovery', 'Error recovery UX', 'Human', 'Recover from error', ['access-denied'], [], [], [], []],
]);

// Domain 5 — Calendar (Track C / A)
add('C', 5, 'Calendar and Time', [
  ['CAL-001', 'Canonical Calendar', 'One canonical Calendar system', 'Human|Organizer', 'Open calendar', ['calendar'], ['calendar'], [], [], ['calendar']],
  ['CAL-002', 'Personal calendar view', 'Personal view', 'Human', 'Personal calendar', ['calendar'], ['calendar'], [], [], []],
  ['CAL-003', 'Team calendar view', 'Team view', 'Team Lead|Human', 'Team calendar', ['calendar'], ['calendar'], [], [], []],
  ['CAL-004', 'Mission calendar view', 'Mission view', 'Organizer', 'Mission calendar', ['calendar'], ['calendar'], [], [], []],
  ['CAL-005', 'Organization calendar view', 'Org view', 'Administrator|Human', 'Org calendar', ['calendar'], ['calendar'], [], [], []],
  ['CAL-006', 'Resource calendar view', 'Resource view', 'Administrator', 'Resource calendar', ['calendar'], ['calendar'], [], [], []],
  ['CAL-007', 'Executive calendar view', 'Executive view', 'Executive', 'Exec calendar', ['calendar'], ['calendar'], [], [], []],
  ['CAL-008', 'Event creation', 'Create events', 'Human', 'Create event', [], ['calendar/events'], [], [], []],
  ['CAL-009', 'Event approval', 'Approve events', 'Administrator|Executive', 'Approve event', [], ['calendar'], [], [], []],
  ['CAL-010', 'Event editing', 'Edit events', 'Human', 'Edit event', [], ['calendar/events'], [], [], []],
  ['CAL-011', 'Recurrence', 'Recurring events', 'Human', 'Set recurrence', [], ['calendar'], [], [], []],
  ['CAL-012', 'Reminders', 'Event reminders', 'Human', 'Get reminder', [], ['calendar'], [], [], []],
  ['CAL-013', 'Deadlines', 'Deadline events', 'Human|Organizer', 'Set deadline', [], ['calendar'], [], [], []],
  ['CAL-014', 'Travel windows', 'Travel windows', 'Executive|Human', 'Block travel', [], ['organizer'], [], [], []],
  ['CAL-015', 'Preparation buffers', 'Prep buffers', 'Human', 'Add prep time', [], ['localbrain', 'meetings'], [], [], []],
  ['CAL-016', 'Availability', 'Availability', 'Human', 'Set availability', [], ['calendar'], [], [], []],
  ['CAL-017', 'Conflict detection', 'Conflict detection', 'Human', 'See conflict', [], ['calendar/conflicts'], [], [], ['calendar']],
  ['CAL-018', 'Time zones', 'Time zone support', 'Human', 'TZ-aware events', [], ['calendar'], [], [], []],
  ['CAL-019', 'External Calendar import', 'Import external calendar', 'Human', 'Import', [], ['calendar'], [], [], []],
  ['CAL-020', 'External Calendar export', 'Export calendar', 'Human', 'Export', [], ['calendar'], [], [], []],
  ['CAL-021', 'Google Calendar integration', 'Google Calendar', 'Human', 'Connect Google', [], ['calendar'], [], [], []],
  ['CAL-022', 'Microsoft Calendar integration', 'Microsoft Calendar', 'Human', 'Connect Microsoft', [], ['calendar'], [], [], []],
  ['CAL-023', 'Apple/ICS compatibility', 'ICS support', 'Human', 'ICS', [], ['calendar'], [], [], []],
  ['CAL-024', 'Calendar permissions', 'Calendar permissions', 'Administrator|Human', 'Perms on calendar', [], ['calendar'], [], [], []],
  ['CAL-025', 'Calendar audit', 'Calendar audit trail', 'Administrator', 'Audit calendar', [], ['calendar'], [], [], []],
  ['CAL-026', 'Calendar-to-Mission linkage', 'Events linked to missions', 'Organizer', 'Link event↔mission', [], ['calendar', 'missions'], [], [], []],
  ['CAL-027', 'Calendar-to-LocalBrain context', 'Calendar feeds LocalBrain', 'Human', 'Context from calendar', [], ['calendar', 'localbrain/context'], [], [], []],
]);

// Domain 6 — Teams (Track D)
add('D', 6, 'Teams, Collaboration, and Human Coordination', [
  ['TEAM-001', 'Team creation', 'Create teams', 'Administrator|Team Lead', 'Create team', [], ['teams'], [], [], []],
  ['TEAM-002', 'Team types', 'Multiple team types', 'Administrator', 'Choose type', [], ['teams'], [], [], []],
  ['TEAM-003', 'Membership', 'Team membership', 'Team Lead|Human', 'Join/leave', ['initiatives', 'people'], [], [], [], []],
  ['TEAM-004', 'Team roles', 'Roles within teams', 'Team Lead', 'Assign role', ['people'], [], [], [], []],
  ['TEAM-005', 'Team home', 'Team home surface', 'Human', 'Open team home', [], [], [], [], []],
  ['TEAM-006', 'Team calendar', 'Team calendar', 'Human', 'Team cal', ['calendar'], ['calendar'], [], [], []],
  ['TEAM-007', 'Team Missions', 'Team missions', 'Organizer|Human', 'Team missions', ['communications/missions', 'missions'], ['missions'], [], [], []],
  ['TEAM-008', 'Team knowledge', 'Team knowledge', 'Human', 'Team knowledge', ['communications/knowledge', 'learning/knowledge'], [], [], [], []],
  ['TEAM-009', 'Team conversations', 'Team conversations', 'Human', 'Talk in team', ['communications'], ['conversations'], [], [], []],
  ['TEAM-010', 'Team files', 'Team files', 'Human', 'Share files', ['communications/documents'], [], [], [], []],
  ['TEAM-011', 'Team meetings', 'Team meetings', 'Human', 'Team meeting', ['communications/meetings'], [], [], [], []],
  ['TEAM-012', 'Team decisions', 'Team decisions', 'Team Lead|Human', 'Decide', ['communications/decisions'], [], [], [], []],
  ['TEAM-013', 'Member directory', 'Directory of people', 'Human', 'Find people', [], ['relationships'], [], [], []],
  ['TEAM-014', 'Availability', 'Member availability', 'Human', 'See availability', [], [], [], [], []],
  ['TEAM-015', 'Cross-team coordination', 'Cross-team work', 'Organizer', 'Coordinate teams', ['initiatives'], [], [], [], []],
  ['TEAM-016', 'Cross-organization teams', 'Cross-org teams', 'Administrator|Partner', 'Cross-org team', ['identity/invitations/cross-institution'], ['federation'], [], [], []],
  ['TEAM-017', 'Volunteer teams', 'Volunteer team spaces', 'Volunteer|Organizer', 'Volunteer team', ['join'], [], [], [], []],
  ['TEAM-018', 'Temporary task forces', 'Task forces', 'Organizer', 'Create task force', [], [], [], [], []],
  ['TEAM-019', 'Committee spaces', 'Committee spaces', 'Board Member|Administrator', 'Committee', [], [], [], [], []],
  ['TEAM-020', 'Board spaces', 'Board spaces', 'Board Member', 'Board home', [], [], [], [], []],
  ['TEAM-021', 'Team onboarding', 'Team onboarding', 'Human', 'Join team onboard', [], [], [], [], []],
  ['TEAM-022', 'Team history', 'Team history', 'Human', 'View history', [], [], [], [], []],
  ['TEAM-023', 'Team archive', 'Archive teams', 'Administrator', 'Archive', [], [], [], [], []],
]);

// Domain 7 — Missions (Track F)
add('F', 7, 'Missions, Projects, and Execution', [
  ['MIS-001', 'Strategic hierarchy', 'Initiative→Objective→Mission hierarchy', 'Executive|Organizer', 'Navigate hierarchy', ['initiatives', 'objectives', 'missions'], ['initiatives', 'objectives'], [], [], []],
  ['MIS-002', 'Goal-to-Mission traceability', 'Trace goals to missions', 'Executive|Organizer', 'Trace', ['initiatives'], ['initiatives', 'objectives'], [], [], []],
  ['MIS-003', 'Mission creation', 'Create missions', 'Organizer', 'Create mission', ['missions', 'objectives'], ['missions', 'objectives'], [], [], []],
  ['MIS-004', 'Mission templates', 'Mission templates', 'Organizer', 'Use template', [], ['missions'], [], [], []],
  ['MIS-005', 'Mission lifecycle', 'Lifecycle states', 'Organizer', 'Advance lifecycle', ['missions', 'closeout'], ['missions', 'operations'], [], [], []],
  ['MIS-006', 'Mission ownership', 'Ownership assigned', 'Organizer', 'Assign owner', ['missions', 'people'], [], [], [], []],
  ['MIS-007', 'Mission teams', 'Teams on missions', 'Organizer', 'Assign team', ['people', 'missions'], [], [], [], []],
  ['MIS-008', 'Mission phases', 'Phases', 'Organizer', 'Manage phases', ['missions', 'workstreams'], [], [], [], []],
  ['MIS-009', 'Activities', 'Activities', 'Organizer|Human', 'Track activities', ['missions', 'progress'], ['operations'], [], [], []],
  ['MIS-010', 'Tasks', 'Tasks', 'Human|Organizer', 'Complete task', ['missions', 'today'], ['operations'], [], [], []],
  ['MIS-011', 'Checklists', 'Checklists', 'Human', 'Checklist', [], [], [], [], []],
  ['MIS-012', 'Dependencies', 'Dependencies', 'Organizer', 'Manage deps', ['dependencies'], [], [], [], []],
  ['MIS-013', 'Milestones', 'Milestones', 'Organizer', 'Milestones', ['progress', 'outcomes'], [], [], [], []],
  ['MIS-014', 'Evidence', 'Evidence capture', 'Human|Organizer', 'Attach evidence', ['evidence'], [], [], [], []],
  ['MIS-015', 'Deliverables', 'Deliverables', 'Organizer', 'Deliverables', ['outcomes'], [], [], [], []],
  ['MIS-016', 'Risks', 'Risk tracking', 'Organizer|Executive', 'Track risks', [], [], [], [], []],
  ['MIS-017', 'Decisions on missions', 'Mission decisions', 'Organizer|Executive', 'Decide', ['decisions', 'approvals'], [], [], [], []],
  ['MIS-018', 'Lessons learned', 'Lessons learned', 'Organizer', 'Capture lessons', ['reviews', 'history'], [], [], [], []],
  ['MIS-019', 'Mission Calendar', 'Mission calendar', 'Organizer', 'Mission calendar', [], ['calendar', 'missions'], [], [], []],
  ['MIS-020', 'Mission communications', 'Mission communications', 'Human|Organizer', 'Mission room', ['communications/missions'], ['communications'], [], [], []],
  ['MIS-021', 'Mission health', 'Health indicators', 'Executive|Organizer', 'View health', ['operations', 'intelligence', 'progress'], ['operations'], [], [], []],
  ['MIS-022', 'Resource assignment', 'Assign resources', 'Organizer', 'Assign resource', [], [], [], [], []],
  ['MIS-023', 'Volunteer assignment', 'Assign volunteers', 'Organizer', 'Assign volunteer', [], [], [], [], []],
  ['MIS-024', 'Project views', 'Project views', 'Organizer', 'Project view', ['initiatives', 'objectives'], [], [], [], []],
  ['MIS-025', 'Kanban', 'Kanban board', 'Organizer|Human', 'Kanban', [], [], [], [], []],
  ['MIS-026', 'Timeline', 'Timeline view', 'Organizer', 'Timeline', [], [], [], [], []],
  ['MIS-027', 'Roadmap', 'Roadmap', 'Executive|Organizer', 'Roadmap', [], [], [], [], []],
  ['MIS-028', 'Field operations', 'Field ops', 'Volunteer|Organizer', 'Field op', ['operations'], ['operations'], [], [], []],
  ['MIS-029', 'Offline field execution', 'Offline field', 'Volunteer', 'Work offline', [], [], [], [], []],
  ['MIS-030', 'Mission completion rules', 'Completion rules', 'Organizer', 'Complete mission', ['closeout', 'missions'], [], [], [], []],
  ['MIS-031', 'Mission archive', 'Archive missions', 'Administrator|Organizer', 'Archive', ['history', 'closeout'], [], [], [], []],
  ['MIS-032', 'Mission-to-knowledge feedback', 'Missions feed knowledge', 'Organizer', 'Promote lessons', ['reviews', 'knowledge'], [], [], [], []],
]);

// Domain 8 — Knowledge (Track E)
add('E', 8, 'Knowledge, Memory, and Search', [
  ['KNO-001', 'Canonical knowledge object', 'Canonical knowledge model', 'Human|Organizer', 'Create knowledge', ['learning/knowledge', 'communications/knowledge'], ['knowledge'], ['builds/11.12'], [], []],
  ['KNO-002', 'Knowledge ingestion', 'Ingest knowledge', 'Human|Organizer', 'Ingest', ['knowledge'], [], [], [], []],
  ['KNO-003', 'Documents', 'Documents as knowledge', 'Human', 'Open document', ['communications/documents'], [], [], [], []],
  ['KNO-004', 'Notes', 'Notes', 'Human', 'Note', [], [], [], [], []],
  ['KNO-005', 'Policies', 'Policies', 'Administrator', 'Policy doc', [], [], [], [], []],
  ['KNO-006', 'Procedures', 'Procedures', 'Human', 'Procedure', [], [], [], [], []],
  ['KNO-007', 'Research knowledge', 'Research artifacts', 'Human|Executive', 'Research', [], ['localbrain/research'], ['living/research'], [], []],
  ['KNO-008', 'Meeting memory', 'Meeting memory', 'Human', 'Recall meeting', ['communications/meetings'], ['conversations'], ['living/conversation'], [], []],
  ['KNO-009', 'Decision knowledge', 'Decisions as knowledge', 'Executive|Human', 'Find decision', ['communications/decisions'], [], [], [], []],
  ['KNO-010', 'Lessons learned knowledge', 'Lessons in knowledge', 'Organizer', 'Find lesson', ['reviews'], [], [], [], []],
  ['KNO-011', 'Templates', 'Templates library', 'Organizer', 'Use template', [], [], [], [], []],
  ['KNO-012', 'Media knowledge', 'Media assets', 'Human', 'Media', [], [], [], [], []],
  ['KNO-013', 'Knowledge permissions', 'Knowledge permissions', 'Administrator', 'Set perms', [], [], [], [], []],
  ['KNO-014', 'Provenance', 'Provenance', 'Human|Administrator', 'See provenance', [], ['genesis', 'provenance'], [], [], []],
  ['KNO-015', 'Version history', 'Version history', 'Human', 'Versions', [], [], [], [], []],
  ['KNO-016', 'Review status', 'Review status', 'Administrator|Human', 'Review', ['reviews'], [], [], [], []],
  ['KNO-017', 'Knowledge promotion', 'Promote knowledge', 'Human|Administrator', 'Promote', [], ['promote-memory'], [], [], []],
  ['KNO-018', 'Knowledge archive', 'Archive knowledge', 'Administrator', 'Archive', [], [], [], [], []],
  ['KNO-019', 'Knowledge search', 'Search knowledge', 'Human', 'Search', ['communications/search', 'learning/knowledge'], ['search'], [], [], []],
  ['KNO-020', 'Natural-language search', 'NL search', 'Human', 'Ask search', ['search'], ['search'], [], [], []],
  ['KNO-021', 'Semantic retrieval', 'Semantic retrieval', 'Human', 'Semantic find', [], ['search', 'intelligence'], [], [], []],
  ['KNO-022', 'Source citations', 'Citations on results', 'Human', 'See sources', [], [], [], [], []],
  ['KNO-023', 'Search filters', 'Filters', 'Human', 'Filter', ['search'], ['search'], [], [], []],
  ['KNO-024', 'Search permission enforcement', 'Search respects perms', 'Administrator|Human', 'Denied results hidden', [], ['search'], [], [], []],
  ['KNO-025', 'Knowledge graph', 'Knowledge graph', 'Human', 'Graph explore', [], [], [], [], []],
  ['KNO-026', 'Topic explorer', 'Topic explorer', 'Human', 'Explore topics', ['learning/knowledge'], [], [], [], []],
  ['KNO-027', 'Timeline view', 'Knowledge timeline', 'Human', 'Timeline', [], ['timeline'], [], [], []],
  ['KNO-028', 'Broken-reference detection', 'Broken refs detected', 'Administrator', 'Fix broken ref', [], [], [], [], []],
  ['KNO-029', 'Duplicate detection', 'Duplicate detection', 'Administrator', 'Dedupe', [], [], [], [], []],
  ['KNO-030', 'Freshness monitoring', 'Freshness', 'Administrator', 'Stale knowledge', [], [], [], [], []],
  ['KNO-031', 'Institutional Brain', 'Institutional brain', 'Executive|Administrator', 'Org intelligence', ['intelligence'], ['intelligence', 'localbrain'], [], [], []],
  ['KNO-032', 'Personal knowledge', 'Personal knowledge', 'Human', 'Personal KB', [], ['localbrain/memory'], [], [], []],
  ['KNO-033', 'Shared knowledge', 'Shared knowledge', 'Human', 'Shared KB', ['knowledge'], [], [], [], []],
  ['KNO-034', 'Public knowledge', 'Public knowledge', 'Guest|Human', 'Public KB', [], ['public'], [], [], []],
]);

export const DOMAIN_META = [
  { id: 1, name: 'Access, Invitation, and Verified Identity', track: 'B' },
  { id: 2, name: 'LocalBrain and Personal Context', track: 'B' },
  { id: 3, name: 'Onboarding and First-Run Experience', track: 'B' },
  { id: 4, name: 'Daily Workspace and Navigation', track: 'C' },
  { id: 5, name: 'Calendar and Time', track: 'C' },
  { id: 6, name: 'Teams, Collaboration, and Human Coordination', track: 'D' },
  { id: 7, name: 'Missions, Projects, and Execution', track: 'F' },
  { id: 8, name: 'Knowledge, Memory, and Search', track: 'E' },
];
