import type { ManualSectionId } from "./nav";

/** What the audience should feel when they leave this page. */
export type PageExperience = {
  feel: string;
  what: string;
  why: string;
  how: string;
  join: string;
  takeaways: string[];
  questions: string[];
  actions: string[];
  speakerNotes: string[];
};

export const PAGE_EXPERIENCE: Record<ManualSectionId, PageExperience> = {
  overview: {
    feel: "Hope",
    what: "A people-powered field strategy for Arkansas.",
    why: "Government works best when communities organize themselves.",
    how: "Every Kelly event launches a permanent organizing effort.",
    join: "Walk the strategy — then own a seat in Benton County.",
    takeaways: [
      "This is not an events calendar. It is an organizing machine.",
      "Every stop leaves the community stronger than before Kelly arrived.",
      "Arkansas glows county by county — starting with Benton.",
    ],
    questions: ["Do you see yourself in this picture?", "What would change if your county ran like this?"],
    actions: ["Open Strategy", "Enter Presentation Mode for the room"],
    speakerNotes: [
      "Sell the vision in under two minutes. Do not bury them in process yet.",
      "Pause on the map glow — let the statewide ambition land.",
    ],
  },
  strategy: {
    feel: "Clarity",
    what: "The entire chain from one event to county victory.",
    why: "People need to see the whole board before they pick a seat.",
    how: "Kelly Event → Local Team → Central → Outreach → Event → Power of 5 → County Growth → Victory.",
    join: "Click each stage. Own one link in the chain.",
    takeaways: [
      "One scheduled event starts a cascade — not a single night.",
      "Local and central work together; neither does it alone.",
      "Victory is what cumulative county strength produces.",
    ],
    questions: ["Which link is missing in your community today?"],
    actions: ["Drill into Event Engine", "Name who owns each stage locally"],
    speakerNotes: ["Treat this as the 30,000-foot board. Interactive, not a lecture."],
  },
  "event-engine": {
    feel: "Wow… this is organized.",
    what: "What happens the moment an event is scheduled.",
    why: "Improvisation loses elections. Standardized activation wins them.",
    how: "One approval branches into County Command, local leads, central teams, outreach, event day, Power of 5, follow-up.",
    join: "Become a local lead or ask Central for a template pack.",
    takeaways: [
      "Approval is the trigger — everything else is choreography.",
      "Graphics, emails, phones, postcards, canvass, media, and registration move on a clock.",
      "Nobody leaves event day without a next step.",
    ],
    questions: ["Who owns the 24-hour follow-up after the first Benton event?"],
    actions: ["Name Event Lead", "Lock first outreach wave dates"],
    speakerNotes: ["Let the branching diagram do the talking. Click boxes. Show discipline."],
  },
  "field-teams": {
    feel: "Belonging",
    what: "Local leadership + central force multipliers.",
    why: "Communities execute. The campaign multiplies.",
    how: "Eight local leads surround the event. Central rings them with specialized support.",
    join: "Pick a local role or a central specialty you can staff.",
    takeaways: [
      "Local teams make it real in the neighborhood.",
      "Central Campaign brings templates, graphics, scripts, and data.",
      "You never have to invent the whole campaign alone.",
    ],
    questions: ["Which seat are you willing to fill this month?"],
    actions: ["Open Local Teams", "Open Central Campaign"],
    speakerNotes: ["Split screen energy: community in the center, HQ around the rim."],
  },
  "local-teams": {
    feel: "Belonging",
    what: "The Local Event Committee.",
    why: "Without named local owners, the engine stalls.",
    how: "Event, Canvass, Social, Registration, Recruitment, Media, Logistics, Community — click a role.",
    join: "Put your name on a seat — or recruit for an open one.",
    takeaways: ["Eight functions. Multiple co-leads allowed.", "Local adapts; Central supplies."],
    questions: ["Which roles are empty in Benton tonight?"],
    actions: ["Fill Event Lead first", "Pair each lead with a co-lead"],
    speakerNotes: ["Expand roles live. Celebrate every name that goes on the map."],
  },
  "central-campaign": {
    feel: "Support",
    what: "Campaign HQ surrounding the counties.",
    why: "Local leaders should not reinvent graphics, scripts, and systems.",
    how: "Email, phone, text, volunteer, young adults, social, postcards, field, media, graphics, county support, operations.",
    join: "Request support through County Command — or staff a central cell.",
    takeaways: ["Center creates the system. Counties adapt it.", "Connection lines are the point — isolation is the enemy."],
    questions: ["What does Benton need from Central in the next 30 days?"],
    actions: ["List first three support requests"],
    speakerNotes: ["Emphasize force-multiplier, not bureaucracy."],
  },
  "regnat-populus": {
    feel: "Pride",
    what: "One campaign. One identity. One movement.",
    why: "Visibility creates belonging — and belonging creates endurance.",
    how: "Wear the mission at canvass, events, registration, Strike Saturdays, and election ops.",
    join: "Wear it. Photograph it. Make Benton unmistakable.",
    takeaways: ["Regnat Populus — The People Rule.", "Same brand in every county.", "Shirts are strategy, not merch."],
    questions: ["Where will Benton be photographed in Regnat Populus first?"],
    actions: ["Plan shirt deployment for first public action"],
    speakerNotes: ["Slow down. This is the emotional peak. Dark stage. Big words. Photos when ready."],
  },
  "power-of-5": {
    feel: "I can actually do this.",
    what: "Relational neighborhood organizing.",
    why: "Attendance fades. Five trusted relationships compound.",
    how: "1 → 5 → 25 → 125 → 625 → Arkansas — grown through people you already know.",
    join: "Become a Power of 5 leader after the next event.",
    takeaways: ["Organic, not mathematical cosplay.", "Primary product of every event funnel.", "Toolkit follows commitment."],
    questions: ["Who are your five?"],
    actions: ["Commit to one P5 launch date after the first event"],
    speakerNotes: ["Walk the cascade slowly. Make agency feel small enough to start tonight."],
  },
  "voter-registration": {
    feel: "Urgency with purpose",
    what: "Registration as a permanent field operation.",
    why: "Ballots are won by people who are on the rolls and show up.",
    how: "Central VR Director → County Lead → Community leads → Volunteers — tied to every event.",
    join: "Take a county or city registration seat.",
    takeaways: ["Not a one-day table.", "Goals by county and city.", "Event funnel always includes a registration step when lawful."],
    questions: ["What is Benton’s first weekly registration habit?"],
    actions: ["Name County VR Lead or mark open"],
    speakerNotes: ["Keep legal practicality visible — never improvise on election law."],
  },
  "strike-teams": {
    feel: "Joy",
    what: "Strike Team Saturdays — festival energy with canvass discipline.",
    why: "People stay when the work feels like community.",
    how: "Stage → deploy → return → food, music, kids, maps, recognition.",
    join: "Pick the first October Saturday Benton will own.",
    takeaways: ["Fun is a retention strategy.", "Every Saturday in October.", "Return with next steps, not just stories."],
    questions: ["Where do we stage? Who brings the grill?"],
    actions: ["Reserve venue window", "Assign Saturday captain"],
    speakerNotes: ["Let this page smile. Music metaphor. Kids. Bounce house. Then the canvass map."],
  },
  "county-command": {
    feel: "Confidence",
    what: "The conductor of the county orchestra.",
    why: "Without an operational home, talent scatters.",
    how: "Dashboard watch: events, volunteers, P5, registration, canvass, media, leadership, support requests.",
    join: "Serve as County Command Lead — or fill a deputy seat.",
    takeaways: ["Connects local leaders; does not replace them.", "Needs Attention is a feature, not a failure.", "Blueprint for future live software."],
    questions: ["Who watches Benton when Kelly leaves town?"],
    actions: ["Name County Command Lead or interim"],
    speakerNotes: ["Ops-center tone. Panels. Calm authority."],
  },
  "election-operations": {
    feel: "Resolve",
    what: "Election Day coverage built month by month.",
    why: "You cannot improvise lawful poll presence in October.",
    how: "State → Region → County → Precinct → Neighborhood → Power of 5.",
    join: "Train for a lawful role — observer, greeter, strike mobile, supply.",
    takeaways: ["Legal clarity before assignment.", "Mobile strike on Election Day.", "Neighborhood links matter."],
    questions: ["How many polling places does Benton need covered?"],
    actions: ["Schedule legal briefing", "Start poll inventory"],
    speakerNotes: ["Serious room. No shortcuts on law."],
  },
  "success-measures": {
    feel: "Focus",
    what: "A framework for what growth looks like.",
    why: "Attendance flatters. Organization decides.",
    how: "Counters for volunteers, leaders, P5, doors, events, registrations, communities — as targets, not fake live stats.",
    join: "Agree what Benton tracks after every event.",
    takeaways: ["Framework numbers, not theater telemetry.", "Continuity beats one-night spikes."],
    questions: ["What is Benton’s infrastructure score after event one?"],
    actions: ["Lock 5 metrics for the first debrief"],
    speakerNotes: ["Animate the counters. Emphasize framework, not fabricated performance."],
  },
  benton: {
    feel: "Ownership",
    what: "Benton County as the model county.",
    why: "Statewide blueprints mean nothing until a county owns them.",
    how: "Map · leadership seats · open positions · events · P5 & registration goals · communities.",
    join: "Put your name on a seat before you leave the room.",
    takeaways: [
      "Benton is not a side quest — it is the proof.",
      "Open positions are invitations, not shame.",
      "Everything becomes local here.",
    ],
    questions: ["Who leads County Command?", "Which city is first?", "When is the first trigger event?"],
    actions: ["Fill leadership map", "Set first event window", "Continue to Join Us"],
    speakerNotes: ["This is the close of the middle act. Names on whiteboards. Ownership energy."],
  },
  join: {
    feel: "Call to action",
    what: "Now what — Benton builds together.",
    why: "Strategy without commitment is a slideshow.",
    how: "Current needs board → volunteer intent (button staged; ops routing later).",
    join: "Raise your hand. Take a seat. Bring five.",
    takeaways: [
      "Let’s Build Benton County Together.",
      "Needs are concrete: Command, City Leads, Canvass, VR, P5, Media, Strike, Events.",
      "The volunteer button is a promise of the next system — not a dead end.",
    ],
    questions: ["What will you own in the next seven days?"],
    actions: ["Declare a seat", "Recruit one peer before you leave"],
    speakerNotes: ["Silence after the headline. Then the needs board. Then the ask."],
  },
};
