import { buildCanonicalEvent } from "./canonical";
import type { CalendarConflict, CalendarEvent } from "./types";

/** Single canonical seed catalog — all calendars reference these by event_id. */
export const SEED_EVENTS: CalendarEvent[] = [
  buildCanonicalEvent({
    event_id: "evt-henderson-vr-drive",
    title: "Henderson State Voter Registration Drive",
    description:
      "First-week back-to-school voter-registration drive on the Henderson State campus. Registration conversations stay separate from VCI and launch-team counts.",
    event_type: "voter_registration_drive",
    operational_status: "scheduled",
    approval_status: "approved",
    publication_status: "published",
    start_at: "2026-08-26T10:00:00-05:00",
    end_at: "2026-08-26T15:00:00-05:00",
    location_name: "Henderson State — Student Union plaza",
    city: "Arkadelphia",
    county: "Clark",
    county_slug: "clark",
    college_slugs: ["henderson-state"],
    county_slugs: ["clark"],
    campaign_wide: true,
    visibility: "public",
    calendar_scope_ids: [
      "universal",
      "college_command",
      "college_community",
      "county",
      "volunteer_management",
      "campaign_operations",
    ],
    public_summary: "Campus voter-registration drive — volunteer shifts open.",
    owned_by_team: "social-events",
    primary_contact: "Campus Voter Registration Lead (interest open)",
    volunteer_manager: "Carol Eagan",
    volunteer_roles: [
      { role_id: "vr-event-lead", title: "Event Lead", number_needed: 1, number_confirmed: 0, training_required: true },
      { role_id: "vr-shift-lead", title: "Shift Lead", number_needed: 2, number_confirmed: 1, training_required: true },
      {
        role_id: "vr-registration",
        title: "Registration Volunteer",
        number_needed: 8,
        number_confirmed: 3,
        training_required: true,
      },
      { role_id: "vr-greeter", title: "Greeter", number_needed: 4, number_confirmed: 1, training_required: false },
    ],
    staffing_status: "needs_volunteers",
    approval_history: [
      {
        at: "2026-07-10T11:00:00-05:00",
        actor: "College Leader (shell)",
        role: "college_leader",
        decision: "approved",
        notes: "Campus window confirmed soft beta.",
        previous_state: "submitted",
        new_state: "approved",
      },
    ],
    history: [{ at: "2026-07-10T11:05:00-05:00", note: "Approved for college, county, and universal calendars." }],
  }),

  buildCanonicalEvent({
    event_id: "evt-uca-networking",
    title: "UCA Networking & Recruitment Night",
    description: "Welcoming campus networking event — not a long political meeting. Follow-up connects guests to teams.",
    event_type: "networking_event",
    operational_status: "confirmed",
    approval_status: "approved",
    publication_status: "published",
    start_at: "2026-07-17T18:00:00-05:00",
    end_at: "2026-07-17T20:00:00-05:00",
    location_name: "UCA Student Center — lobby",
    city: "Conway",
    county: "Faulkner",
    county_slug: "faulkner",
    college_slugs: ["uca"],
    county_slugs: ["faulkner"],
    campaign_wide: false,
    visibility: "public",
    calendar_scope_ids: ["universal", "college_community", "college_command", "county", "volunteer_management"],
    owned_by_team: "social-events",
    volunteer_manager: "Carol Eagan",
    volunteer_roles: [
      { role_id: "net-host", title: "Event Host", number_needed: 2, number_confirmed: 2, training_required: false },
      { role_id: "net-greeter", title: "Greeter", number_needed: 4, number_confirmed: 2, training_required: false },
    ],
    kelly_requested: true,
    kelly_attendance_status: "under_review",
    kelly_role: "Brief welcome remarks",
    travel_required: true,
    security_or_private_notes: "PRIVATE: tentative arrival 17:20 via internal travel desk — not for public calendars.",
    kelly_arrival_time: "2026-07-17T17:20:00-05:00",
    kelly_departure_time: "2026-07-17T20:15:00-05:00",
    public_summary: "Campus networking night. Special guest attendance requested — not confirmed.",
    history: [{ at: "2026-06-28T12:00:00-05:00", note: "Campus Event Lead confirmed venue." }],
  }),

  buildCanonicalEvent({
    event_id: "evt-ualr-vr-tabling",
    title: "UA Little Rock Voter Registration Tabling",
    description: "Welcome-week tabling with registration team. Metrics stay labeled separately.",
    event_type: "voter_registration_drive",
    operational_status: "scheduled",
    approval_status: "approved",
    publication_status: "ready_to_publish",
    start_at: "2026-08-25T11:00:00-05:00",
    end_at: "2026-08-25T15:00:00-05:00",
    location_name: "UA Little Rock — Donaghey Student Center",
    city: "Little Rock",
    county: "Pulaski",
    county_slug: "pulaski",
    college_slugs: ["ua-little-rock"],
    county_slugs: ["pulaski"],
    visibility: "public",
    volunteer_roles: [
      {
        role_id: "ualr-reg",
        title: "Registration Volunteer",
        number_needed: 10,
        number_confirmed: 4,
        training_required: true,
      },
    ],
    history: [{ at: "2026-07-05T09:00:00-05:00", note: "Registration lane linked tabling shift." }],
  }),

  buildCanonicalEvent({
    event_id: "evt-pulaski-weekend-canvass",
    title: "Pulaski Weekend Canvass",
    description: "Neighborhood turf walk with county canvass lead.",
    event_type: "canvass",
    operational_status: "scheduled",
    approval_status: "approved",
    publication_status: "published",
    start_at: "2026-07-19T09:00:00-05:00",
    end_at: "2026-07-19T12:00:00-05:00",
    location_name: "Hillcrest meet-up",
    city: "Little Rock",
    county: "Pulaski",
    county_slug: "pulaski",
    county_slugs: ["pulaski"],
    campaign_wide: false,
    visibility: "public",
    volunteer_roles: [
      { role_id: "canvass-walk", title: "Canvass Volunteer", number_needed: 12, number_confirmed: 5, training_required: true },
    ],
    assigned_human_ids: ["usr-demo-001"],
    history: [{ at: "2026-07-08T10:00:00-05:00", note: "County board posted turf." }],
  }),

  buildCanonicalEvent({
    event_id: "evt-volunteer-training-kickoff",
    title: "Volunteer Training Kickoff",
    description: "Opening session for field volunteer training — Event Board coordinated.",
    event_type: "volunteer_training",
    operational_status: "confirmed",
    approval_status: "approved",
    publication_status: "published",
    start_at: "2026-08-15T09:00:00-05:00",
    end_at: "2026-08-15T12:00:00-05:00",
    location_name: "Block Street Training Center — Meeting Room A",
    city: "Little Rock",
    county: "Pulaski",
    county_slug: "pulaski",
    county_slugs: ["pulaski"],
    campaign_wide: true,
    visibility: "public",
    calendar_scope_ids: ["universal", "volunteer_management", "campaign_operations", "college_command"],
    volunteer_manager: "Carol Eagan",
    volunteer_roles: [
      { role_id: "train-host", title: "Training Host", number_needed: 2, number_confirmed: 2, training_required: false },
      { role_id: "train-participant", title: "Trainee seat", number_needed: 24, number_confirmed: 11, training_required: false },
    ],
    assigned_human_ids: ["usr-demo-001"],
    history: [{ at: "2026-07-01T10:00:00-05:00", note: "Confirmed statewide training date." }],
  }),

  buildCanonicalEvent({
    event_id: "evt-kelly-campus-hold-asu",
    title: "Kelly campus appearance — Arkansas State (hold)",
    description: "Candidate appearance request under scheduling review. Private travel details stay internal.",
    event_type: "candidate_appearance",
    operational_status: "tentative",
    approval_status: "under_review",
    publication_status: "internal_only",
    start_at: "2026-08-28T16:00:00-05:00",
    end_at: "2026-08-28T17:00:00-05:00",
    location_name: "ASU Student Union (requested)",
    city: "Jonesboro",
    county: "Craighead",
    county_slug: "craighead",
    college_slugs: ["arkansas-state"],
    county_slugs: ["craighead"],
    visibility: "command",
    kelly_requested: true,
    kelly_attendance_status: "hold_placed",
    kelly_role: "Listening session",
    travel_required: true,
    security_or_private_notes: "PRIVATE lodging and route — never publish.",
    kelly_arrival_time: "2026-08-28T15:15:00-05:00",
    kelly_departure_time: "2026-08-28T17:30:00-05:00",
    public_summary: null,
    conflict_ids: ["conf-kelly-asu-buffer"],
    conflict_state: "possible_conflict",
    calendar_scope_ids: ["candidate", "college_command", "volunteer_management", "campaign_operations"],
    history: [{ at: "2026-07-12T14:00:00-05:00", note: "Hold placed pending CM + Kelly desk review." }],
  }),

  buildCanonicalEvent({
    event_id: "evt-ops-committee-review",
    title: "Operations Committee Review",
    description: "Internal planning — not public.",
    event_type: "leadership_meeting",
    operational_status: "scheduled",
    approval_status: "pending",
    publication_status: "internal_only",
    start_at: "2026-08-20T14:00:00-05:00",
    end_at: "2026-08-20T15:30:00-05:00",
    location_name: "Block Street Training Center",
    city: "Little Rock",
    county_slug: "pulaski",
    county_slugs: ["pulaski"],
    campaign_wide: true,
    visibility: "command",
    calendar_scope_ids: ["campaign_operations", "universal"],
    assigned_human_ids: ["usr-demo-001"],
    history: [{ at: "2026-07-13T08:55:00-05:00", note: "Scheduled on operations calendar." }],
  }),

  buildCanonicalEvent({
    event_id: "evt-college-command-kickoff",
    title: "College Command summer kickoff",
    description: "Cross-campus leads sync — Event Board and CM present.",
    event_type: "leadership_meeting",
    operational_status: "confirmed",
    approval_status: "approved",
    publication_status: "internal_only",
    start_at: "2026-07-21T17:00:00-05:00",
    end_at: "2026-07-21T18:00:00-05:00",
    location_name: "Virtual",
    city: null,
    campaign_wide: true,
    visibility: "team",
    calendar_scope_ids: ["college_command", "campaign_operations", "volunteer_management"],
    volunteer_manager: "Carol Eagan",
    history: [{ at: "2026-07-11T09:00:00-05:00", note: "Confirmed virtual kickoff." }],
  }),
];

export const SEED_CONFLICTS: CalendarConflict[] = [
  {
    conflict_id: "conf-kelly-asu-buffer",
    event_ids: ["evt-kelly-campus-hold-asu", "evt-henderson-vr-drive"],
    summary: "Possible travel buffer conflict if Kelly hold consolidates to southwest Arkansas same week — human review required.",
    severity: "medium",
    state: "possible_conflict",
  },
];

/** Future city calendars are schema-ready; no active city dashboards required in this slice. */
export const FUTURE_CITY_CALENDAR_READY = true as const;
